basePath: /v1
host: localhost:8020
info:
  contact:
    email: moecods.dev@gmail.com
    name: API Support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /quizzes/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Show an account
      tags:
      - quizes
swagger: "2.0"
