basePath: /v1
definitions:
  participant.Answer:
    properties:
      answer_text:
        type: string
      answered_at:
        type: string
      id:
        type: string
      is_correct:
        type: boolean
      question_id:
        type: string
      selection_option:
        type: integer
    type: object
  participant.ParticipantAnswer:
    properties:
      answers:
        items:
          $ref: '#/definitions/participant.Answer'
        type: array
      participant_id:
        type: string
    type: object
  participant.RegisterRequest:
    properties:
      number_of_participants:
        type: integer
      quiz_id:
        type: string
    type: object
  participant.SaveParticipantsAnswersRequest:
    properties:
      participant_answers:
        items:
          $ref: '#/definitions/participant.ParticipantAnswer'
        type: array
    type: object
  quiz.Question:
    properties:
      correct_option:
        type: integer
      id:
        type: string
      options:
        items:
          type: string
        type: array
      text:
        type: string
      type:
        description: 'Type of question: "descriptive" or "test"'
        type: string
    type: object
  quiz.Quiz:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      questions:
        items:
          $ref: '#/definitions/quiz.Question'
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8020
info:
  contact:
    email: moecods.dev@gmail.com
    name: API Support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /participants/answers:
    post:
      consumes:
      - application/json
      description: Save participants answers
      parameters:
      - description: Save participants answers Request object
        in: body
        name: SaveParticipantsAnswersRequest
        required: true
        schema:
          $ref: '#/definitions/participant.SaveParticipantsAnswersRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to read request body
          schema:
            type: string
      summary: Save participants answers
      tags:
      - participants
  /participants/register:
    post:
      consumes:
      - application/json
      description: Register participants
      parameters:
      - description: Register Request object
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/participant.RegisterRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to read request body
          schema:
            type: string
      summary: Register participants
      tags:
      - participants
  /quizzes:
    post:
      consumes:
      - application/json
      description: Add an quiz
      parameters:
      - description: Quiz object
        in: body
        name: quiz
        required: true
        schema:
          $ref: '#/definitions/quiz.Quiz'
      produces:
      - application/json
      responses:
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to read request body
          schema:
            type: string
      summary: Add a quiz
      tags:
      - quizzes
  /quizzes/{id}:
    delete:
      consumes:
      - application/json
      description: delete an quiz
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Invalid request body
          schema:
            type: string
      summary: delete a quiz
      tags:
      - quizzes
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Show an quiz
      tags:
      - quizzes
    put:
      consumes:
      - application/json
      description: Update an existing quiz by ID
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      - description: Quiz object
        in: body
        name: quiz
        required: true
        schema:
          $ref: '#/definitions/quiz.Quiz'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/quiz.Quiz'
        "400":
          description: Invalid quiz ID or request body
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a quiz
      tags:
      - quizzes
swagger: "2.0"
